### ISSUE TITLE
验证或者支持在更高的 LTS 版本运行

### ISSUE THREAD

**Issue by Createsequence** [opengoofy/crane4j#11]
目标是适配 11 和 17，预期将会调整三部分内容：
- [x] core 模块本体；
- [x] spring 扩展；
- [x] mp 扩展；
- [x] springboot 的 starter 扩展；

**Comment by Createsequence** [comment]
2023-07-06 补充：
我们在分支 feat/java-lts-support 上进行了验证，并成功升级了 JDK、SpringBoot、MybatisPlus 以及相关组件的依赖。结果显示，crane4j 在这些升级后的环境下可以正常运行。目前我们只发现了一些与 SpringBoot 和 MP 等第三方库之间兼容性的问题。然而，只要用户的项目中的对应依赖可以兼容，覆盖 crane4j 后仍然可以正常运行。

尽管如此，我们目前还不能断定升级过程一定不会产生任何问题。后续我们将在其他独立项目中进行进一步测试，以确认其无缝升级的可行性。

**Comment by iko233** [comment]
JDK17的环境下LambdaContainer.forLambda方法下使用Function.identity()编译时会出现以下错误
cn/crane4j/spring/boot/example/ManyToManyAssembleExampleTest.java#init

不兼容的类型: 推断类型不符合下限
    推断: cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo
    下限: java.lang.Object,cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo

Function.identity()更换为item->item暂可运行

**Comment by Createsequence** [comment]
> JDK17的环境下LambdaContainer.forLambda方法下使用Function.identity()编译时会出现以下错误 cn/crane4j/spring/boot/example/ManyToManyAssembleExampleTest.java#init
> 
> 不兼容的类型: 推断类型不符合下限 推断: cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo 下限: java.lang.Object,cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo
> 
> Function.identity()更换为item->item暂可运行

有兴趣提个PR吗？

**Comment by iko233** [comment]
> > JDK17的环境下LambdaContainer.forLambda方法下使用Function.identity()编译时会出现以下错误 cn/crane4j/spring/boot/example/ManyToManyAssembleExampleTest.java#init
> > 不兼容的类型: 推断类型不符合下限 推断: cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo 下限: java.lang.Object,cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo
> > Function.identity()更换为item->item暂可运行
> 
> 有兴趣提个PR修复一下这个问题吗？

这个似乎是jdk17的泛型判断存在问题，我无法提供一个较好的解决方案，目前只有几个不完美的方案
1. 更换Function.identity()为item->item
2.显式声明LambdaContainer类型      LambdaContainer.forLambda    ->   LambdaContainer.<Integer>forLambda
3.显示声明Function.identity()类型。 -> Function.<Integer>identity();

**Comment by Createsequence** [comment]
> > > JDK17的环境下LambdaContainer.forLambda方法下使用Function.identity()编译时会出现以下错误 cn/crane4j/spring/boot/example/ManyToManyAssembleExampleTest.java#init
> > > 不兼容的类型: 推断类型不符合下限 推断: cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo 下限: java.lang.Object,cn.crane4j.spring.boot.example.ManyToManyAssembleExampleTest.Foo
> > > Function.identity()更换为item->item暂可运行
> > 
> > 
> > 有兴趣提个PR修复一下这个问题吗？
> 
> 这个似乎是jdk17的泛型判断存在问题，我无法提供一个较好的解决方案，目前只有几个不完美的方案
> 
> 1. 更换Function.identity()为item->item
>    2.显式声明LambdaContainer类型      LambdaContainer.forLambda    ->   `LambdaContainer.<Integer>forLambda`
>    3.显示声明Function.identity()类型。 -> `Function.<Integer>identity()`;

我觉得第三个方案不错。

另外，我也觉得这个问题在 JDK8 的环境下没有出现确实挺诡异的。
