### ISSUE TITLE
当目标对象的key值与数据源对象的key值类型不一致时，可以指定将目标对象的key值转为对应类型

### ISSUE THREAD

**Issue by urzeye** [opengoofy/crane4j#153]
`getTheAssociatedSource` 方法根据key找数据源时未做自动类型转换，如`sources`和`target`中的key类型不一致可能导致无法映射
![image](https://github.com/opengoofy/crane4j/assets/20869204/e27fd814-a7f2-43f7-98a8-4163f94c08ca)
![image](https://github.com/opengoofy/crane4j/assets/20869204/42660408-ac6b-41be-899f-5741f1577668)
![image](https://github.com/opengoofy/crane4j/assets/20869204/5f67e82d-4467-4153-9cb7-478c1ada5eae)

**Comment by Createsequence** [comment]
站在 crane4j 的角度，由于数据源五花八门，数据源里面拿到数据用什么类型的 key 来分类的这个是无法确定的，所以这个要自动推断可能不太现实。

不过，可以考虑在下一个版本添加一个在 `@AssembleXXX` 注解手动指定 key 类型的功能，比如：
~~~java
@Assemble(container = "foo", keyType = Long.class, props = @Mapping("name"))
private Integer id;
~~~
这样的话在 `getTheAssociatedSource` 方法里面就可以先判断一样，如果从待填充对象取到的 key 类型与指定的类型不一样，就先转换一下。
