### ISSUE TITLE
`@AssembleEnum` 直接直接内嵌一个 `@ContainerEnum` 注解用于配置

### ISSUE THREAD

**Issue by Createsequence** [opengoofy/crane4j#176]
`@AssembleEnum` 应当支持直接内嵌一个 `@ContainerEnum` 注解用于配置，就像 `@AssembleEnum` 内嵌 `@ContainerMethod` 一样。

按此规划，则下述配置：
~~~java
@AssembleEnum(
    type = Gender.class, 
    enumKey = "code", enumValue = "value"
)
public Integer gender;
~~~
等同于
~~~java
@AssembleEnum(
    type = Gender.class, 
    config = @ContainerEnum(key = "code", value = "value")
)
public Integer gender;
~~~

并且，当如此调整后，原本的 `useContainerEnum` 属性的含义将会变的模糊，应当更名为 `followTypeConfig`。

**上述修改将不对 2.3 版本进行兼容，因此需要在文档中进行特别强调。**

- [x] 调整代码；
- [x] 修改文档；

**Comment by wybaby168** [comment]
大佬，请问这个项目稳定吗，能在生产环境中用否？

**Comment by Createsequence** [comment]
> 大佬，请问这个项目稳定吗，能在生产环境中用否？

可以的，2.3.0 已经在我们的生产环境稳定运行挺久的了。
