### ISSUE TITLE
为基于 `ConstantContainer` 的枚举、常量容器提供独立的`Builder`

### ISSUE THREAD

**Issue by Createsequence** [opengoofy/crane4j#77]
现有基于基于 `ConstantContainer` 的枚举、常量容器构建过程过于复杂了，而且构建逻辑直接放到 `ConstantContainer` 也违背了单一职责原则，让 `ConstantContainer` 变得非常臃肿，因此希望能够将枚举和常量两种容器的构建过程抽离至独立的 `Builder` 中。

**Comment by tangcent** [comment]
我尝试处理这个issue: #111

但看起来`EnumContainer`和`ConstantContainer`没有足够的复杂度来继承`Container`，或者说如果他们继承`ImmutableMapContainer`，他们似乎也没有额外的逻辑。

**Comment by Createsequence** [comment]
> 我尝试处理这个issue: #111
> 
> 但看起来`EnumContainer`和`ConstantContainer`没有足够的复杂度来继承`Container`，或者说如果他们继承`ImmutableMapContainer`，他们似乎也没有额外的逻辑。

确实是这样的。

实际上不管是基于枚举还是常量，本质上都是基于 `Map` 的内存容器，所以你的的 PR 是非常正确的，我们只需要一个 `ImmutableMapContainer` 一个容器的实现类就够了，`ConstantContainer` 应当作为一个单纯的静态工厂类，或者直接把里面的 `forEnum` 和 `forConstantClass` 静态方法合并到 `Containers` 里面。

然后就是我们在 PR 里面讨论的东西了，你希望静态工厂能够根据容器的类型做个区分，也就是分离成独立的 `EnumContainer` 和 `ConstantContainer`，但是不在令其作为 `Container` 的实现类，而仅作为与 `Containers` 同级的静态工厂，而我的观点是，没必要区分 `EnumContainer` 或者 `ConstantContainer`，所有的工厂方法都统一合并到 `Containers` 里面即可，不过正如所说，枚举和常量容器的创建逻辑直接通通塞到 `Containers` 里面有点不够优雅。

实际上也是这个 issue 想要解决的问题。基于枚举或者常量类创建容器的逻辑是比较麻烦的，有些选项目前还必须依赖注解去配置，从我个人的角度来看，最好枚举和常量容器的构建逻辑都分离到一个 `Builder` 中，比如：
~~~java
Container<Object> container = new ConstantContainerBuilder(Constant.class)
    .forAnnotation(new AnnotationFinder()) // 启用注解配置
    .onlyExplicitlyIncluded(true) // 覆盖注解配置 onlyExplicitlyIncluded
    .namespace("foo_constant") // 覆盖注解配置 namespace
    .build();
~~~
这样一来，`Builder` 就将解析类并构建容器的逻辑分离开来了。在这个基础上，静态工厂类 `Containers` 就可以基于 `Builder` 以默认的配置快速构建容器，而不必承担过多的额外逻辑，就像 Spring 中 `MergedAnnotation` 与 `AnnotationElementUtil` 的关系那样。

**Comment by tangcent** [comment]
我非常赞同你的观点
